import React,{useEffect,useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import './style.css';

const API=(import.meta.env.VITE_API_URL||'http://localhost:10000/api').replace(/\/$/,'');
const GRADES=[1,2,3,4,5,6];
const TYPES=['찾아오는 체험학습','공연·문화예술','생태·환경','진로·직업','안전·생활','교육과정 연계','기타'];
const recs=['적극 추천','추천','조건부 추천','비추천'];
async function api(path,opt={}){const r=await fetch(API+path,{headers:{'Content-Type':'application/json',...(opt.headers||{})},...opt});let d={};try{d=await r.json()}catch{}if(!r.ok)throw new Error(d.message||'요청에 실패했습니다.');return d}
const auth=t=>({Authorization:`Bearer ${t}`});
function GradeTags({values=[]}){return <div className="grades">{values.map(g=><span key={g}>{g}학년</span>)}</div>}
function App(){const [grade,setGrade]=useState('');const [q,setQ]=useState('');const [list,setList]=useState([]);const [selected,setSelected]=useState(null);const [admin,setAdmin]=useState(false);const [login,setLogin]=useState(false);const [loading,setLoading]=useState(true);const load=async()=>{setLoading(true);try{setList(await api(`/activities?grade=${grade}&q=${encodeURIComponent(q)}`))}catch(e){alert(e.message)}finally{setLoading(false)}};useEffect(()=>{load()},[grade]);useEffect(()=>{const t=setTimeout(load,250);return()=>clearTimeout(t)},[q]);
return <><header><div className="nav"><div className="brand"><span className="logo">A</span><div><b>우리학교 교육활동 아카이브</b><small>다음 학년도의 선택을 돕는 운영 경험 기록</small></div></div><button className="adminLink" onClick={()=>setLogin(true)}>관리자</button></div><section className="hero"><span className="eyebrow">SCHOOL EDUCATIONAL ACTIVITY ARCHIVE</span><h1>작년의 운영 경험을<br/><em>내년의 선택으로</em></h1><p>우리 학교에서 실제 운영한 교육활동의 정보와 경험을 한눈에 확인하세요.</p></section></header>
<main><div className="toolbar"><div className="filter"><button className={!grade?'active':''} onClick={()=>setGrade('')}>전체</button>{GRADES.map(g=><button key={g} className={grade==g?'active':''} onClick={()=>setGrade(String(g))}>{g}학년</button>)}</div><input value={q} onChange={e=>setQ(e.target.value)} placeholder="교육활동명 또는 운영기관 검색"/></div>{loading?<div className="empty">교육활동을 불러오는 중...</div>:list.length===0?<div className="empty"><b>등록된 교육활동이 없습니다.</b><br/>관리자에서 첫 교육활동을 등록해 주세요.</div>:<div className="grid">{list.map(a=><article className="card" key={a.id} onClick={()=>setSelected(a.id)}><div className="cardTop"><span className="type">{a.activity_type}</span>{a.latest_year&&<span className="year">최근 {a.latest_year}년</span>}</div><h2>{a.name}</h2><p>{a.description||'등록된 프로그램 소개가 없습니다.'}</p><div className="provider">{a.provider||'운영기관 미입력'} {a.duration_minutes?`· ${a.duration_minutes}분`:''}</div><GradeTags values={a.available_grades}/><div className="result">{a.latest_satisfaction?<><strong>★ {Number(a.latest_satisfaction).toFixed(1)}</strong><span>{a.latest_recommendation}</span></>:<span>운영 기록 준비 중</span>}<small>운영 기록 {a.record_count}건</small></div></article>)}</div>}</main>{selected&&<Detail id={selected} onClose={()=>setSelected(null)}/>} {login&&<AdminLogin onClose={()=>setLogin(false)} onSuccess={()=>{setLogin(false);setAdmin(true)}}/>}{admin&&<Admin onClose={()=>setAdmin(false)} onChanged={load}/>}</>}
function Detail({id,onClose}){const [d,setD]=useState(null);useEffect(()=>{api(`/activities/${id}`).then(setD).catch(e=>alert(e.message))},[id]);if(!d)return <div className="overlay"><div className="modal"><button className="x" onClick={onClose}>×</button><div className="empty">불러오는 중...</div></div></div>;const a=d.activity;return <div className="overlay" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><div className="modal detail"><button className="x" onClick={onClose}>×</button><span className="type">{a.activity_type}</span><h2>{a.name}</h2><p className="lead">{a.description||'등록된 프로그램 소개가 없습니다.'}</p><div className="info"><div><small>운영기관</small><b>{a.provider||'-'}</b></div><div><small>소요시간</small><b>{a.duration_minutes?`${a.duration_minutes}분`:'-'}</b></div><div><small>신청 가능 학년</small><GradeTags values={a.available_grades}/></div></div><h3>연도별 운영 기록</h3>{d.records.length===0?<div className="empty">아직 운영 기록이 없습니다.</div>:d.records.map(r=><div className="record" key={r.id}><div className="recordHead"><strong>{r.school_year}년</strong><span>실제 운영 <b>{r.operated_grades.map(g=>g+'학년').join(', ')}</b></span><span>{r.overall_satisfaction?`만족도 ★ ${Number(r.overall_satisfaction).toFixed(1)}`:'만족도 미입력'}</span><span className={'recommend '+r.recommendation}>{r.recommendation}</span></div><div className="recordGrid"><div><small>사용 예산</small><b>{r.budget!=null?Number(r.budget).toLocaleString()+'원':'-'}</b></div><div><small>장점</small><p>{r.pros||'-'}</p></div><div><small>단점</small><p>{r.cons||'-'}</p></div></div>{r.additional_comment&&<div className="comment"><small>추가 의견</small><p>{r.additional_comment}</p></div>}</div>)}</div></div>}
function AdminLogin({onClose,onSuccess}){const [pw,setPw]=useState('');const [busy,setBusy]=useState(false);const submit=async e=>{e.preventDefault();setBusy(true);try{const d=await api('/admin/login',{method:'POST',body:JSON.stringify({password:pw})});localStorage.setItem('v4admin',d.token);onSuccess()}catch(e){alert(e.message)}finally{setBusy(false)}};return <div className="overlay"><form className="modal small" onSubmit={submit}><button type="button" className="x" onClick={onClose}>×</button><span className="eyebrow">ADMIN</span><h2>관리자 로그인</h2><p>교육활동과 연도별 운영 기록을 관리합니다.</p><input autoFocus type="password" value={pw} onChange={e=>setPw(e.target.value)} placeholder="관리자 비밀번호"/><button className="primary" disabled={busy}>{busy?'확인 중...':'로그인'}</button></form></div>}
function Admin({onClose,onChanged}){const token=localStorage.getItem('v4admin');const [items,setItems]=useState([]);const [editing,setEditing]=useState(null);const [recordFor,setRecordFor]=useState(null);const load=()=>api('/admin/activities',{headers:auth(token)}).then(setItems).catch(()=>{localStorage.removeItem('v4admin');onClose()});useEffect(()=>{load()},[]);return <div className="overlay adminOverlay"><div className="modal adminModal"><button className="x" onClick={onClose}>×</button><div className="adminTitle"><div><span className="eyebrow">ADMIN</span><h2>교육활동 관리</h2></div><button className="ghost" onClick={()=>setEditing({})}>+ 교육활동 등록</button></div><p className="muted">교육활동 기본정보를 등록한 뒤, 연도별 운영 기록을 추가하세요.</p><div className="adminList">{items.map(a=><div className="adminItem" key={a.id}><div><b>{a.name}</b><span>{a.activity_type} · 신청 가능 {a.available_grades.join(', ')}학년</span></div><div><button className="ghost" onClick={()=>setRecordFor(a)}>운영 기록</button><button className="ghost" onClick={()=>setEditing(a)}>수정</button></div></div>)}</div>{editing!==null&&<ActivityForm token={token} initial={editing} onClose={()=>setEditing(null)} onSaved={()=>{setEditing(null);load();onChanged()}}/>}{recordFor&&<RecordForm token={token} activity={recordFor} onClose={()=>setRecordFor(null)} onSaved={()=>{setRecordFor(null);load();onChanged()}}/>}</div></div>}
function ActivityForm({token,initial,onClose,onSaved}){const [f,setF]=useState({name:'',activity_type:TYPES[0],provider:'',description:'',duration_minutes:'',available_grades:[],...initial});const toggle=g=>setF({...f,available_grades:f.available_grades.includes(g)?f.available_grades.filter(x=>x!==g):[...f.available_grades,g].sort()});const submit=async e=>{e.preventDefault();try{await api(initial.id?`/admin/activities/${initial.id}`:'/admin/activities',{method:initial.id?'PUT':'POST',headers:auth(token),body:JSON.stringify(f)});onSaved()}catch(e){alert(e.message)}};return <div className="innerOverlay"><form className="modal formModal" onSubmit={submit}><button type="button" className="x" onClick={onClose}>×</button><h2>{initial.id?'교육활동 수정':'교육활동 등록'}</h2><label>교육활동명<input required value={f.name} onChange={e=>setF({...f,name:e.target.value})}/></label><label>교육활동 유형<select value={f.activity_type} onChange={e=>setF({...f,activity_type:e.target.value})}>{TYPES.map(x=><option key={x}>{x}</option>)}</select></label><label>운영 기관/업체<input value={f.provider||''} onChange={e=>setF({...f,provider:e.target.value})}/></label><label>소요 시간(분)<input type="number" min="0" value={f.duration_minutes||''} onChange={e=>setF({...f,duration_minutes:e.target.value})}/></label><label>프로그램 소개<textarea value={f.description||''} onChange={e=>setF({...f,description:e.target.value})}/></label><div className="gradePicker"><b>신청 가능한 학년</b><div>{GRADES.map(g=><button type="button" key={g} className={f.available_grades.includes(g)?'selected':''} onClick={()=>toggle(g)}>{g}학년</button>)}</div></div><button className="primary">저장</button></form></div>}
function RecordForm({token,activity,onClose,onSaved}){const [f,setF]=useState({school_year:new Date().getFullYear(),budget:'',overall_satisfaction:'',recommendation:'추천',pros:'',cons:'',additional_comment:'',reviewer_name:'',operated_grades:activity.available_grades||[]});const toggle=g=>setF({...f,operated_grades:f.operated_grades.includes(g)?f.operated_grades.filter(x=>x!==g):[...f.operated_grades,g].sort()});const submit=async e=>{e.preventDefault();try{await api(`/admin/activities/${activity.id}/records`,{method:'POST',headers:auth(token),body:JSON.stringify(f)});onSaved()}catch(e){alert(e.message)}};return <div className="innerOverlay"><form className="modal formModal wide" onSubmit={submit}><button type="button" className="x" onClick={onClose}>×</button><span className="type">{activity.name}</span><h2>연도별 운영 기록</h2><p className="muted">같은 연도에 다시 저장하면 기존 기록을 수정합니다.</p><div className="two"><label>운영 연도<input type="number" min="2000" max="2100" value={f.school_year} onChange={e=>setF({...f,school_year:e.target.value})}/></label><label>사용 예산(원)<input type="number" min="0" value={f.budget} onChange={e=>setF({...f,budget:e.target.value})}/></label></div><label>실제 운영 학년<div className="gradePicker">{GRADES.map(g=><button type="button" key={g} className={f.operated_grades.includes(g)?'selected':''} onClick={()=>toggle(g)}>{g}학년</button>)}</div></label><div className="two"><label>종합 만족도(1~5)<input type="number" min="1" max="5" step="0.1" value={f.overall_satisfaction} onChange={e=>setF({...f,overall_satisfaction:e.target.value})}/></label><label>재실시 추천<select value={f.recommendation} onChange={e=>setF({...f,recommendation:e.target.value})}>{recs.map(x=><option key={x}>{x}</option>)}</select></label></div><label>작성자<input value={f.reviewer_name} onChange={e=>setF({...f,reviewer_name:e.target.value})}/></label><label>장점<textarea value={f.pros} onChange={e=>setF({...f,pros:e.target.value})}/></label><label>단점<textarea value={f.cons} onChange={e=>setF({...f,cons:e.target.value})}/></label><label>추가 의견<textarea value={f.additional_comment} onChange={e=>setF({...f,additional_comment:e.target.value})}/></label><button className="primary">운영 기록 저장</button></form></div>}

createRoot(document.getElementById('root')).render(<App/>);
