import React,{useEffect,useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import './style.css';

const API=(import.meta.env.VITE_API_URL||'http://localhost:10000/api').replace(/\/$/,'');
const cats=['전체','교육과정','체험활동','행사','연수','기타'];
const api=async(path,opt={})=>{const r=await fetch(API+path,{...opt,headers:{'Content-Type':'application/json',...(opt.headers||{})}});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.message||'오류가 발생했습니다.');return d;};
const authHeader=(token)=>({Authorization:`Bearer ${token}`});
function Stars({value=0,onChange,large=false}){return <div className={'stars '+(large?'large':'')} aria-label={`${value}점`}>{[1,2,3,4,5].map(n=><button type="button" key={n} onClick={()=>onChange?.(n)} className={n<=value?'on':''}>★</button>)}</div>}
function App(){
 const [activities,setActivities]=useState([]),[cat,setCat]=useState('전체'),[selected,setSelected]=useState(null),[loading,setLoading]=useState(true),[memberToken,setMemberToken]=useState(localStorage.getItem('memberToken')||''),[adminToken,setAdminToken]=useState(localStorage.getItem('adminToken')||''),[memberLogin,setMemberLogin]=useState(false),[adminLogin,setAdminLogin]=useState(false),[admin,setAdmin]=useState(false),[toast,setToast]=useState('');
 const load=async()=>{setLoading(true);try{setActivities(await api('/activities'));}catch(e){setToast(e.message)}finally{setLoading(false)}};useEffect(()=>{load()},[]);
 const open=async id=>{try{setSelected(await api(`/activities/${id}`))}catch(e){setToast(e.message)}};
 const logoutMember=()=>{localStorage.removeItem('memberToken');setMemberToken('')}; const logoutAdmin=()=>{localStorage.removeItem('adminToken');setAdminToken('');setAdmin(false)};
 const filtered=useMemo(()=>activities.filter(a=>cat==='전체'||a.category===cat),[activities,cat]);
 return <><header><div className="wrap nav"><div><div className="brand">우리학교 교육활동 리뷰</div><div className="sub">함께 돌아보고, 더 나은 교육활동을 만들어요.</div></div><div className="navBtns">{memberToken?<button className="ghost" onClick={logoutMember}>학교 구성원 로그아웃</button>:<button className="ghost" onClick={()=>setMemberLogin(true)}>학교 구성원 로그인</button>}{adminToken?<button className="ghost" onClick={()=>setAdmin(!admin)}>{admin?'일반 화면':'관리자'}</button>:<button className="ghost" onClick={()=>setAdminLogin(true)}>관리자</button>}</div></div></header>
 <main className="wrap">{admin&&<Admin token={adminToken} onChanged={load} onLogout={logoutAdmin}/>}<section className="hero"><div><span className="eyebrow">SCHOOL ACTIVITY REVIEW</span><h1>우리 학교 교육활동,<br/><span>함께 평가하고 기록해요.</span></h1><p>학교 구성원만 리뷰를 작성할 수 있으며, 화면에는 익명으로 표시됩니다.</p><div className="heroBtns"><button className="primary" onClick={()=>memberToken?null:setMemberLogin(true)}>{memberToken?'학교 구성원 인증 완료':'학교 구성원으로 참여하기'}</button></div></div></section>
 <div className="filters">{cats.map(c=><button key={c} className={cat===c?'active':''} onClick={()=>setCat(c)}>{c}</button>)}</div>
 {loading?<div className="empty">교육활동을 불러오는 중...</div>:<div className="grid">{filtered.map(a=><article className="card" key={a.id} onClick={()=>open(a.id)}><div className="cardTop"><span className="tag">{a.category}</span><span className="date">{a.activity_date||''}</span></div><h2>{a.title}</h2><p>{a.description||'등록된 설명이 없습니다.'}</p><div className="rating"><span>★</span> {Number(a.average_rating).toFixed(1)} <small>· 리뷰 {a.review_count}개</small></div></article>)}</div>}
 {filtered.length===0&&!loading&&<div className="empty">등록된 교육활동이 없습니다.</div>}</main>
 {selected&&<Detail data={selected} memberToken={memberToken} onNeedLogin={()=>setMemberLogin(true)} onClose={()=>setSelected(null)} onSaved={()=>open(selected.activity.id)}/>} {memberLogin&&<MemberLogin onClose={()=>setMemberLogin(false)} onSuccess={t=>{setMemberToken(t);localStorage.setItem('memberToken',t);setMemberLogin(false)}}/>}{adminLogin&&<AdminLogin onClose={()=>setAdminLogin(false)} onSuccess={t=>{setAdminToken(t);localStorage.setItem('adminToken',t);setAdmin(true);setAdminLogin(false)}}/>}{toast&&<div className="toast" onClick={()=>setToast('')}>{toast}</div>}</>;
}
function MemberLogin({onClose,onSuccess}){const [code,setCode]=useState('');const submit=async e=>{e.preventDefault();try{const d=await api('/member/login',{method:'POST',body:JSON.stringify({accessCode:code})});onSuccess(d.token)}catch(e){alert(e.message)}};return <div className="modalBg"><form className="modal small" onSubmit={submit}><button type="button" className="close" onClick={onClose}>×</button><span className="eyebrow">MEMBER ACCESS</span><h2>학교 구성원 인증</h2><p className="muted">학교에서 안내받은 구성원 인증코드를 입력하세요.</p><input autoFocus type="password" placeholder="인증코드" value={code} onChange={e=>setCode(e.target.value)}/><button className="primary">인증하고 참여하기</button></form></div>}
function AdminLogin({onClose,onSuccess}){const [pw,setPw]=useState('');const submit=async e=>{e.preventDefault();try{const d=await api('/admin/login',{method:'POST',body:JSON.stringify({password:pw})});onSuccess(d.token)}catch(e){alert(e.message)}};return <div className="modalBg"><form className="modal small" onSubmit={submit}><button type="button" className="close" onClick={onClose}>×</button><span className="eyebrow">ADMIN</span><h2>관리자 로그인</h2><input autoFocus type="password" placeholder="관리자 비밀번호" value={pw} onChange={e=>setPw(e.target.value)}/><button className="primary">로그인</button></form></div>}
function Detail({data,memberToken,onNeedLogin,onClose,onSaved}){const [mine,setMine]=useState(null);const [form,setForm]=useState({rating:5,educational_effect:5,student_participation:5,operation_ease:5,reuse_intention:5,comment:''});const [busy,setBusy]=useState(false);useEffect(()=>{if(memberToken)api('/my-reviews',{headers:authHeader(memberToken)}).then(xs=>{if(xs.some(x=>x.activity_id===data.activity.id)){/* 서버는 본문을 노출하지 않으므로 현재 작성 여부만 표시 */}}).catch(()=>{})},[memberToken,data.activity.id]);const submit=async e=>{e.preventDefault();if(!memberToken){onNeedLogin();return}setBusy(true);try{await api(`/activities/${data.activity.id}/reviews`,{method:'POST',headers:authHeader(memberToken),body:JSON.stringify(form)});setMine(true);await onSaved()}catch(e){alert(e.message)}finally{setBusy(false)}};return <div className="modalBg" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><div className="modal detail"><button className="close" onClick={onClose}>×</button><span className="tag">{data.activity.category}</span><h2>{data.activity.title}</h2><p className="muted">{data.activity.description}</p><div className="summary"><div><b>{Number(data.stats.average).toFixed(1)}</b><Stars value={Math.round(Number(data.stats.average))}/><small>리뷰 {data.stats.count}개</small></div><div className="mini"><span>교육적 효과 <b>{data.stats.educational_effect}</b></span><span>학생 참여도 <b>{data.stats.student_participation}</b></span><span>운영 편의성 <b>{data.stats.operation_ease}</b></span><span>재실행 의향 <b>{data.stats.reuse_intention}</b></span></div></div><form onSubmit={submit} className="reviewForm"><h3>{mine?'내 리뷰 수정':'리뷰 남기기'}</h3><label>종합 별점 <Stars large value={form.rating} onChange={v=>setForm({...form,rating:v})}/></label>{[['educational_effect','교육적 효과'],['student_participation','학생 참여도'],['operation_ease','운영 편의성'],['reuse_intention','재실행 의향']].map(([k,l])=><label key={k}>{l}<Stars value={form[k]} onChange={v=>setForm({...form,[k]:v})}/></label>)}<textarea maxLength="300" placeholder="짧은 코멘트를 남겨주세요. (300자 이내)" value={form.comment} onChange={e=>setForm({...form,comment:e.target.value})}/><button className="primary" disabled={busy}>{busy?'등록 중...':memberToken?'리뷰 등록 / 수정':'로그인 후 리뷰 작성'}</button></form><div className="reviews"><h3>다른 선생님들의 리뷰</h3>{data.reviews.length===0?<p className="muted">아직 리뷰가 없습니다.</p>:data.reviews.map(r=><div className="review" key={r.id}><div><Stars value={r.rating}/><small>{new Date(r.created_at).toLocaleDateString('ko-KR')}</small></div><p>{r.comment||'코멘트 없음'}</p></div>)}</div></div></div>}
function Admin({token,onChanged,onLogout}){const empty={title:'',category:'교육과정',activity_date:'',description:''};const [f,setF]=useState(empty),[dash,setDash]=useState(null),[tab,setTab]=useState('dashboard');const load=async()=>{try{setDash(await api('/admin/dashboard',{headers:authHeader(token)}))}catch(e){alert(e.message)}};useEffect(()=>{load()},[]);const save=async e=>{e.preventDefault();try{await api('/activities',{method:'POST',headers:authHeader(token),body:JSON.stringify(f)});setF(empty);await load();onChanged()}catch(e){alert(e.message)}};const del=async id=>{if(!confirm('이 교육활동과 리뷰를 모두 삭제할까요?'))return;try{await api(`/activities/${id}`,{method:'DELETE',headers:authHeader(token)});await load();onChanged()}catch(e){alert(e.message)}};const exportXlsx=async()=>{const r=await fetch(API+'/admin/export.xlsx',{headers:authHeader(token)});if(!r.ok){alert('다운로드 권한이 없습니다.');return}const blob=await r.blob();const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='school-activity-review.xlsx';a.click();URL.revokeObjectURL(url)};return <section className="admin"><div className="adminHead"><div><span className="eyebrow">ADMIN DASHBOARD</span><h2>교육활동 평가 관리</h2></div><div className="adminBtns"><button className="ghost" onClick={exportXlsx}>Excel 다운로드</button><button className="ghost" onClick={onLogout}>로그아웃</button></div></div><div className="adminTabs"><button className={tab==='dashboard'?'active':''} onClick={()=>setTab('dashboard')}>통계</button><button className={tab==='add'?'active':''} onClick={()=>setTab('add')}>교육활동 추가</button></div>{tab==='dashboard'&&!dash?<p>불러오는 중...</p>:tab==='dashboard'&&dash?<><div className="kpis"><div><b>{dash.total.activities}</b><span>교육활동</span></div><div><b>{dash.total.reviews}</b><span>전체 리뷰</span></div><div><b>{dash.activities[0]?dash.activities[0].average_rating:'0.0'}</b><span>최고 평균점수</span></div></div><h3>활동별 평가</h3><div className="tableWrap"><table><thead><tr><th>교육활동</th><th>분류</th><th>리뷰</th><th>평균</th><th>교육효과</th><th>참여도</th><th>운영</th><th>재실행</th><th></th></tr></thead><tbody>{dash.activities.map(a=><tr key={a.id}><td>{a.title}</td><td>{a.category}</td><td>{a.review_count}</td><td>⭐ {a.average_rating}</td><td>{a.educational_effect}</td><td>{a.student_participation}</td><td>{a.operation_ease}</td><td>{a.reuse_intention}</td><td><button className="danger" onClick={()=>del(a.id)}>삭제</button></td></tr>)}</tbody></table></div></>:<form onSubmit={save} className="adminForm"><input required placeholder="교육활동명" value={f.title} onChange={e=>setF({...f,title:e.target.value})}/><select value={f.category} onChange={e=>setF({...f,category:e.target.value})}>{cats.slice(1).map(c=><option key={c}>{c}</option>)}</select><input type="date" value={f.activity_date} onChange={e=>setF({...f,activity_date:e.target.value})}/><input placeholder="간단한 설명" value={f.description} onChange={e=>setF({...f,description:e.target.value})}/><button className="primary">교육활동 추가</button></form>}</section>}
createRoot(document.getElementById('root')).render(<App/>);
